### ISSUE TITLE
Jonny's TODO's

### ISSUE THREAD

**Issue by william-taylor** [wt-student-projects/serious-games-coursework#3]
- Fire Effects
- Timer
- Video 
- Collision

**Comment by william-taylor** [comment]
@CaptainSeagull

**Comment by CaptainSeagull** [comment]
I made a repo (which is basically a copy of yours) and put my shit here. I've only done the timer and fire, because the video's are being a bitch.

https://github.com/CaptainSeagull/Serious-Games

**Comment by CaptainSeagull** [comment]
@william-taylor
